server:
  port: 8086

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Create a client ID
            client-secret: Fetch you client secret from Github and paste here
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma4:e4b
      embedding:
        model: nomic-embed-text
    vectorstore:
      chroma:
        initialize-schema: true
        client:
          host: http://localhost
          port: 8000